environment:
    development:
      source:
          api_url: "https://automationexercise.com/api"
          base_url: "https://automationexercise.com"
          auth_url: "https://automationexercise.com/login"
          products_url: "https://automationexercise.com/products"
          home_url: "https://automationexercise.com/"
